[package]
name = "plays"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "plays"

[dependencies]
hdk = "0.3"
serde = "1"
plays_integrity = { path = "../integrity" }
catalog_integrity = { path = "../../catalog/integrity" }
